---
version: "3.7"
services:
  evolutionjxysvx7:
    image: davidsongomes/evolution-api:latest
    hostname: evolutionjxysvx7
    volumes:
    - evolutionjxysvx7_instances:/evolution/instances
    - evolutionjxysvx7_store:/evolution/store
    networks:
    - network_public
    environment:
    - DOCKER_ENV=true
    - SERVER_URL=https://apiwhats.leaoequipamentos.com.br
    - LOG_LEVEL=ERROR,INFO
    - DEL_INSTANCE=false
    - AUTHENTICATION_TYPE=apikey
    - AUTHENTICATION_API_KEY=52561919-8ed9-4aaa-9abb-6957bbb27999
    - AUTHENTICATION_EXPOSE_IN_FETCH_INSTANCES=true
    - WEBHOOK_GLOBAL_ENABLED=false
    - WEBHOOK_GLOBAL_URL=
    - WEBHOOK_GLOBAL_WEBHOOK_BY_EVENTS=false
    - WEBHOOK_EVENTS_STATUS_INSTANCE=true
    - WEBHOOK_EVENTS_QRCODE_UPDATED=true
    - WEBHOOK_EVENTS_MESSAGES_SET=false
    - WEBHOOK_EVENTS_MESSAGES_UPDATE=true
    - WEBHOOK_EVENTS_MESSAGES_UPSERT=true
    - WEBHOOK_EVENTS_SEND_MESSAGE=true
    - WEBHOOK_EVENTS_CONTACTS_SET=false
    - WEBHOOK_EVENTS_CONTACTS_UPSERT=true
    - WEBHOOK_EVENTS_CONTACTS_UPDATE=true
    - WEBHOOK_EVENTS_PRESENCE_UPDATE=false
    - WEBHOOK_EVENTS_CHATS_SET=false
    - WEBHOOK_EVENTS_CHATS_UPSERT=true
    - WEBHOOK_EVENTS_CHATS_UPDATE=true
    - WEBHOOK_EVENTS_CONNECTION_UPDATE=true
    - WEBHOOK_EVENTS_GROUPS_UPSERT=true
    - WEBHOOK_EVENTS_GROUPS_UPDATE=true
    - WEBHOOK_EVENTS_GROUP_PARTICIPANTS_UPDATE=true
    - CONFIG_SESSION_PHONE_CLIENT=evolution
    - CONFIG_SESSION_PHONE_NAME=Chrome
    - QRCODE_LIMIT=30
    - REDIS_ENABLED=false
    - REDIS_URI=redis://redis:6379
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
        - node.role == manager
      labels:
      - traefik.enable=1
      - traefik.http.routers.evolutionjxysvx7.rule=Host(`apiwhats.leaoequipamentos.com.br`)
      - traefik.http.routers.evolutionjxysvx7.entrypoints=websecure
      - traefik.http.routers.evolutionjxysvx7.priority=1
      - traefik.http.routers.evolutionjxysvx7.tls.certresolver=letsencryptresolver
      - traefik.http.routers.evolutionjxysvx7.service=evolutionjxysvx7
      - traefik.http.services.evolutionjxysvx7.loadbalancer.server.port=8080
      - traefik.http.services.evolutionjxysvx7.loadbalancer.passHostHeader=1
volumes:
  evolutionjxysvx7_instances:
    external: true
    name: evolutionjxysvx7_instancesd
  evolutionjxysvx7_store:
    external: true
    name: evolutionjxysvx7_stored
networks:
  network_public:
    name: network_swarm_public
    external: true
...
