---
version: "3.7"
services:
  n8ni42kknx_admin:
    image: n8nio/n8n:latest
    entrypoint: tini -- /docker-entrypoint.sh
    command: start
    networks:
    - network_public
    environment:
    - DB_TYPE=postgresdb
    - DB_POSTGRESDB_DATABASE=n8ni42kknx
    - DB_POSTGRESDB_HOST=postgres
    - DB_POSTGRESDB_PORT=5432
    - DB_POSTGRESDB_USER=postgres
    - DB_POSTGRESDB_PASSWORD=pm9Be00s44SiKodc
    - N8N_ENCRYPTION_KEY=hBiSlBwcAO76nTAy
    - N8N_HOST=n8ndev.leaoequipamentos.com.br
    - N8N_EDITOR_BASE_URL=https://n8ndev.leaoequipamentos.com.br/
    - N8N_PROTOCOL=https
    - NODE_ENV=production
    - WEBHOOK_URL=https://n8nwebhook.leaoequipamentos.com.br/
    - EXECUTIONS_MODE=queue
    - QUEUE_BULL_REDIS_HOST=redis
    - QUEUE_BULL_REDIS_PORT=6379
    - QUEUE_BULL_REDIS_PASSWORD=pCKJGOaU2L65YL3B
    - QUEUE_BULL_REDIS_DB=3
    - NODE_FUNCTION_ALLOW_EXTERNAL=moment,lodash,moment-with-locales
    - EXECUTIONS_DATA_PRUNE=true
    - EXECUTIONS_DATA_MAX_AGE=336
    - GENERIC_TIMEZONE=America/Sao_Paulo
    - TZ=America/Sao_Paulo
    volumes:
    - n8ni42kknx_data:/data/backup
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
        - node.role == manager
      labels:
      - traefik.enable=1
      - traefik.http.routers.n8ni42kknx_a.rule=Host(`n8ndev.leaoequipamentos.com.br`)
      - traefik.http.routers.n8ni42kknx_a.entrypoints=websecure
      - traefik.http.routers.n8ni42kknx_a.priority=2
      - traefik.http.routers.n8ni42kknx_a.tls.certresolver=letsencryptresolver
      - traefik.http.routers.n8ni42kknx_a.service=n8ni42kknx_a
      - traefik.http.services.n8ni42kknx_a.loadbalancer.server.port=5678
      - traefik.http.services.n8ni42kknx_a.loadbalancer.passHostHeader=1
  n8ni42kknx_webhook:
    image: n8nio/n8n:latest
    entrypoint: tini -- /docker-entrypoint.sh
    command: webhook
    networks:
    - network_public
    environment:
    - DB_TYPE=postgresdb
    - DB_POSTGRESDB_DATABASE=n8ni42kknx
    - DB_POSTGRESDB_HOST=postgres
    - DB_POSTGRESDB_PORT=5432
    - DB_POSTGRESDB_USER=postgres
    - DB_POSTGRESDB_PASSWORD=pm9Be00s44SiKodc
    - N8N_ENCRYPTION_KEY=hBiSlBwcAO76nTAy
    - N8N_HOST=n8ndev.leaoequipamentos.com.br
    - N8N_EDITOR_BASE_URL=https://n8ndev.leaoequipamentos.com.br/
    - N8N_PROTOCOL=https
    - NODE_ENV=production
    - WEBHOOK_URL=https://n8nwebhook.leaoequipamentos.com.br/
    - EXECUTIONS_MODE=queue
    - QUEUE_BULL_REDIS_HOST=redis
    - QUEUE_BULL_REDIS_PORT=6379
    - QUEUE_BULL_REDIS_PASSWORD=pCKJGOaU2L65YL3B
    - QUEUE_BULL_REDIS_DB=3
    - NODE_FUNCTION_ALLOW_EXTERNAL=moment,lodash,moment-with-locales
    - EXECUTIONS_DATA_PRUNE=true
    - EXECUTIONS_DATA_MAX_AGE=336
    - GENERIC_TIMEZONE=America/Sao_Paulo
    - TZ=America/Sao_Paulo
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
        - node.role == manager
      labels:
      - traefik.enable=1
      - traefik.http.routers.n8ni42kknx_w.rule=(Host(`n8nwebhook.leaoequipamentos.com.br`))
      - traefik.http.routers.n8ni42kknx_w.entrypoints=websecure
      - traefik.http.routers.n8ni42kknx_w.priority=1
      - traefik.http.routers.n8ni42kknx_w.tls.certresolver=letsencryptresolver
      - traefik.http.routers.n8ni42kknx_w.service=n8ni42kknx_w
      - traefik.http.services.n8ni42kknx_w.loadbalancer.server.port=5678
      - traefik.http.services.n8ni42kknx_w.loadbalancer.passHostHeader=1
  n8ni42kknx_worker:
    image: n8nio/n8n:latest
    entrypoint: tini -- /docker-entrypoint.sh
    command: worker --concurrency=5
    networks:
    - network_public
    environment:
    - DB_TYPE=postgresdb
    - DB_POSTGRESDB_DATABASE=n8ni42kknx
    - DB_POSTGRESDB_HOST=postgres
    - DB_POSTGRESDB_PORT=5432
    - DB_POSTGRESDB_USER=postgres
    - DB_POSTGRESDB_PASSWORD=pm9Be00s44SiKodc
    - N8N_ENCRYPTION_KEY=hBiSlBwcAO76nTAy
    - N8N_HOST=n8ndev.leaoequipamentos.com.br
    - N8N_EDITOR_BASE_URL=https://n8ndev.leaoequipamentos.com.br/
    - N8N_PROTOCOL=https
    - NODE_ENV=production
    - WEBHOOK_URL=https://n8nwebhook.leaoequipamentos.com.br/
    - EXECUTIONS_MODE=queue
    - QUEUE_BULL_REDIS_HOST=redis
    - QUEUE_BULL_REDIS_PORT=6379
    - QUEUE_BULL_REDIS_PASSWORD=pCKJGOaU2L65YL3B
    - QUEUE_BULL_REDIS_DB=3
    - NODE_FUNCTION_ALLOW_EXTERNAL=moment,lodash,moment-with-locales
    - EXECUTIONS_DATA_PRUNE=true
    - EXECUTIONS_DATA_MAX_AGE=336
    - GENERIC_TIMEZONE=America/Sao_Paulo
    - TZ=America/Sao_Paulo
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
        - node.role == manager
      labels:
      - traefik.enable=
volumes:
  n8ni42kknx_data:
    external: true
    name: n8ni42kknx_datad
networks:
  network_public:
    name: network_swarm_public
    external: true
...
