version: '3.7'
services:
    postgres:
        image: postgres:14
        environment:
            - POSTGRES_PASSWORD=pm9Be00s44SiKodc
        networks:
            - network_public
        volumes:
            - postgres_data:/var/lib/postgresql/data
        deploy:
            mode: replicated
            replicas: 1
            placement:
                constraints:
                    - node.role == manager
volumes:
    postgres_data:
        external: true
        name: postgres_data
networks:
    network_public:
        external: true
        name: network_swarm_public