version: '3.7'
services:
    redis:
        image: redis:latest
        networks:
            - network_public
        volumes:
            - redis_data:/data
        deploy:
            placement:
                constraints: [node.role == manager]
        command: ["redis-server", "--appendonly", "yes"]
volumes:
    redis_data:
networks:
    network_public:
        external: true
        name: network_swarm_public